version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  odoo:
    image: odoo-development:${odoo_version}
    build:
      context: ./odoo
    command: --dev=all
    ports:
      - "8069:8069"
    volumes:
      - "./odoo/${odoo_version}/odoo.conf:/etc/odoo/odoo.conf:ro"
      - "./addons:/mnt/extra-addons"
    depends_on:
      - db

